

services:
  dhcp-server:
    image: nilessh/dhcp-server:${DHCP_SERVER_VERSION}
    container_name: dhcp-server
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - DHCP_INTERFACE=ens37
    volumes:
      - ./dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - /home/it22093264/vcct-assignment/dhcp-serve/dhcpd-data:/var/lib/dhcpd
    restart: unless-stopped

  dns-server:
    image: nilessh/dns-server:${DNS_SERVER_VERSION}
    container_name: dns-server
    depends_on:
      - dhcp-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns-server/named.conf:/etc/named.conf:ro
      - ./dns-server/forward.vcct.com:/var/named/forward.vcct.com:ro
      - ./dns-server/reverse.vcct.com:/var/named/reverse.vcct.com:ro
      - /home/it22093264/vcct-assignment/dns-server/logs:/var/log/named
    restart: unless-stopped

  squid-proxy:
    image: nilessh/squid-proxy:${SQUID_PROXY_VERSION}
    container_name: squid-proxy-4
    depends_on:
      - dhcp-server
    ports:
      - "3128:3128"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    volumes:
      - /home/it22093264/vcct-assignment/squid-proxy/logs:/var/log/squid
      - ./squid-proxy/squid.conf:/etc/squid/squid.conf:ro
      - ./squid-proxy/banned-keywords:/etc/squid/banned-keywords:ro
      - ./squid-proxy/blocked-filextensions:/etc/squid/blocked-filextensions:ro
      - ./squid-proxy/blocked-sites:/etc/squid/blocked-sites:ro
    restart: unless-stopped
