acl localnet src 192.168.8.0/24
acl http_ports port 80



acl blocked_sites dstdomain "/etc/squid/blocked-sites"
http_access deny blocked_sites

acl blockfiles urlpath_regex -i "/etc/squid/blocked-filextensions"
http_access deny blockfiles

acl keyword-ban url_regex "/etc/squid/banned-keywords"
http_access deny keyword-ban

http_access allow localnet http_ports

http_access deny all
cache_dir ufs /var/spool/squid 100 16 256
http_port 3128
coredump_dir /var/spool/squid
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
